minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@mad-c/file-system-helpers@1.1.0"
  - "@mad-c/config"
trustPolicy: "no-downgrade"
preferFrozenLockfile: true
ignoreScripts: true
ignoreDepScripts: true
strictDepBuilds: true
engineStrict: false
ignorePnpmfile: true
blockExoticSubdeps: true
allowBuilds:
