import { SdrButton } from './button/button';
import { SdrDialog } from './dialog/dialog';
import { SdrDropArea } from './drop-area/drop-area';
import { SdrDropdown } from './dropdown-menu/dropdown-menu';
import { SdrDropdownItem } from './dropdown-menu-item/dropdown-menu-item';
import { SdrEditBox } from './edit-box/edit-box';
import { SdrEditList } from './edit-list/edit-list';
import { SdrEditListItem } from './edit-list-item/edit-list-item';
import { SdrSelect } from './edit-select/edit-select';
import { SdrTextArea } from './edit-textarea/edit-textarea';
import { SdrCard } from './item-card/item-card';
import { SdrProgressOverlay } from './progress/progress';
import { SdrLoader } from './skeleton-loader/skeleton-loader';
import { SdrUpdateNotify } from './update-notify/update-notify';
import { SdrMenuBar } from './menu-bar/menu-bar';
import { SdrSearchBox } from './search-box/search-box';
import { SdrRadioGroup } from './radio-group/radio-group';
import { SdrRadioItem } from './radio-item/radio-item';

customElements.define('sdr-button', SdrButton);
customElements.define('sdr-dialog', SdrDialog);
customElements.define('sdr-drop-area', SdrDropArea);
customElements.define('sdr-dropdown', SdrDropdown);
customElements.define('sdr-dropdown-item', SdrDropdownItem);
customElements.define('sdr-edit-box', SdrEditBox);
customElements.define('sdr-edit-list', SdrEditList);
customElements.define('sdr-edit-list-item', SdrEditListItem);
customElements.define('sdr-select', SdrSelect);
customElements.define('sdr-textarea', SdrTextArea);
customElements.define('sdr-card', SdrCard);
customElements.define('sdr-progress-overlay', SdrProgressOverlay);
customElements.define('sdr-loader', SdrLoader);
customElements.define('sdr-update-notify', SdrUpdateNotify);
customElements.define('sdr-menu-bar', SdrMenuBar);
customElements.define('sdr-search-box', SdrSearchBox);
customElements.define('sdr-radio-group', SdrRadioGroup);
customElements.define('sdr-radio-item', SdrRadioItem);
