// @ts-nocheck
export const ColorSpaces={JCS_UNKNOWN:0,JCS_GRAYSCALE:1,JCS_RGB:2,JCS_YCbCr:3,JCS_CMYK:4,JCS_YCCK:5,JCS_EXT_RGB:6,JCS_EXT_RGBX:7,JCS_EXT_BGR:8,JCS_EXT_BGRX:9,JCS_EXT_XBGR:10,JCS_EXT_XRGB:11,JCS_EXT_RGBA:12,JCS_EXT_BGRA:13,JCS_EXT_ABGR:14,JCS_EXT_ARGB:15,JCS_RGB565:16};
